-- Schema de resíduos e pontos de coleta (ReNovaAI)

begin;

create schema if not exists extensions;
create extension if not exists pg_trgm with schema extensions;
create extension if not exists unaccent with schema extensions;

-- categorias exibidas na tela inicial.
create table if not exists categorias (
    id integer generated by default as identity primary key,
    nome varchar(100) not null unique,
    icone varchar(50)
);

-- Residuos e a orientação de descarte (a orientação sempre vem daqui, nunca da IA)
create table if not exists residuos (
    id integer generated by default as identity primary key,
    categoria_id integer not null references categorias(id),
    nome varchar(150) not null unique,
    orientacao_descarte text not null,
    cuidados text,
    nao_fazer text,
    reciclavel boolean not null default false,
    risco boolean not null default false,
    ativo boolean not null default true,
    constraint risco_exige_cuidados check (not risco or cuidados is not null)
);

-- Palavra do dia a dia que levam ao residuo: "latinha" > "lata de aluminio".
create table if not exists sinonimos (
    id integer generated by default as identity primary key,
    residuo_id integer not null references residuos(id) on delete cascade,
    termo varchar(100) not null,
    unique (residuo_id, termo)
);

-- Pontos de coleta. Horário vazio = "horário não disponivel"; veridicado = false = "informação a confirmar". 
create table if not exists pontos_coleta (
    id integer generated by default as identity primary key,
    nome varchar(150) not null,
    endereco varchar(255) not null,
    lat double precision not null,
    lng double precision not null,
    horario varchar(255),
    contato varchar(255),
    verificado boolean not null default false,
    ativo boolean not null default true,
    unique (nome, endereco)
);

-- Quais residuos cada ponto aceita.
create table if not exists ponto_residuo (
    ponto_id integer not null references pontos_coleta(id) on delete cascade,
    residuo_id integer not null references residuos(id) on delete cascade,
    primary key (ponto_id, residuo_id)
);

--Configurações lidas pelas funções sql (raios de busca em km)
create table if not exists configuracoes (
    chave text primary key,
    valor numeric not null
);

-- Segurança: com RLS ligado e sem policies, a API pública do Supabase não enxerga nada.
-- Só o backend (conexão direta como postgres) acessa os dados.
alter table categorias    enable row level security;
alter table residuos      enable row level security;
alter table sinonimos     enable row level security;
alter table pontos_coleta enable row level security;
alter table ponto_residuo enable row level security;
alter table configuracoes enable row level security;

commit; 